---
title: "hw6 - kmeans metastasis"
author: "Jeremy Leipzig"
date: "3/1/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(EBImage)
library(wvtool)
library(stringr)

set.seed(1)
```

## Test kmeans implementation
### Provided test
```{r}
source("hwkmeans.R")
d<-read.table(header = TRUE, text = "5 2
4 1
3 5
2 4
1 3
9 4
9 6
10 7
11 6
10 4
6 4")

hwkmeans(d)
```

\pagebreak

### Test iris flowers dataset
Each panel is an iteration of the kmeans clustering implementation

```{r}
irisres<-hwkmeans(iris[,1:4])

irisres$plot
```

Let's compare this to the flower species
```{r}
names(irisres$calls)<-iris$Species
irisres$calls
```

\pagebreak

## Test metastasis data
```{r}
imagedir<-"hwkmeans.metastasis/img/"
candidates<-dir(imagedir)[grep("(normal)|(metastasis)",dir(imagedir))]

getimagerow<-function(file){
  img<-readImage(paste(imagedir,file,sep=""))
  colorMode(img)<-Grayscale
  imgdata<-imageData(img)[,,1]
  imghist<-hist(imgdata,breaks=seq(0,1,by=0.01),plot=FALSE)$counts
  lbphist<-hist(lbp(imgdata)$lbp.u2,breaks=seq(0,59,by=1),plot=FALSE)$counts
  return(c(imghist,lbphist))
}

imgmatrix<-t(sapply(candidates,getimagerow))
metares<-hwkmeans(imgmatrix)
metares
```

## How was the concordance?
```{r}
get_accuracy<-function(resulttable){
  #assumes NEG POS columns and rows
  #Classification accuracy
  #(TP + TN) / (TP + TN + FP + FN)
  TN<-resulttable[1,1]
  TP<-resulttable[2,2]
  FN<-resulttable[2,1]
  FP<-resulttable[1,2]
  accuracy <- ((TP + TN) / (TP + TN + FP + FN))
  return(accuracy)
}

#this will depend on which cluster happens to be called TRUE
obs<-str_detect(names(metares$calls),'normal')
pred<-metares$calls
ct<-table(obs,pred)
accuracy<-max(get_accuracy(ct),1-get_accuracy(ct))
```

Accuracy is `r accuracy`. Ugh.
